

<form id="searchEngine" class="form-search" action="/search?is_news=true&is_service=true&is_organisation=true" method="GET" onsubmit="if(getElementById('search_string').value == '') {alert('Поле поиска не может быть пустым!'); return false; }">
	<input class="search-query" type="text" placeholder="Поиск" name="search_string" id="search_string" />
	<?php if (!isset($showFull)): ?>
	<?php $showFull = 'hidden'; ?>
	<?php else: ?>
		<p>Искать по разделам:</p>
	<?php endif; ?>
	
	<div class="hidden">
		<input type="hidden" name="news_flag" value="true" />
		<input type="hidden" name="service_flag" value="true" />
		<input type="hidden" name="organisation_flag" value="true" />

	</div>
</form>
