<div class="main">
	<div class="prev"><img src="/templates/newdesign/images/leftArr.jpg" alt="" title=""></div>
	
	<div class="gallery">
		<ul>
		<?php //print_r($subservices); ?>
		<?php for ($i = 0; $i <= 7; $i++): ?>
			<li class="parent" style="height: 72px;">
				<div class="for_align">
					<div class="child"><a href="/services?operation=subservice&subservice_id=<?php echo $subservices[$i]['id']; ?>" title="<?php echo $subservices[$i]['subservice_name']; ?>"><?php echo $subservices[$i]['subservice_name']; ?></a></div>
				</div>
			</li>
		<?php endfor; ?>
		</ul>					
	</div>
	<div class="next"><img src="/templates/newdesign/images/rightArr.jpg" alt="" title=""></div>
	<script>				
		jQuery(".gallery").jCarouselLite({
			btnNext: ".next",
			btnPrev: ".prev",
			liHeight: 72
			
		});
	</script>
</div>
<div class="cl"></div>

