


<table class="table table-bordered">
	<tr>
		<td>
			<b>Ф.И.О. заявителя</b>
		</td>
		<td>
			<b>Контакты</b>
		</td>
		<td>
			<b>Текст</b>
		</td>
		<td>
			<b>Дата обращения</b>
		</td>
		<td>
			<b>Статус</b>
		</td>
		<td></td>
	</tr>
	<?php if (!empty($feedbacks)): ?>
		<?php foreach ($feedbacks as $feedback): ?>	    
		<?php 	
			if ($feedback['status'] == 0) {
				$status = '<span class="error_msg">Не обработано</span>';
			} else {
				$status = '<span class="success_msg">Обработано</span>';
			}
		?>	
	<tr>
		<td>
			<?php echo $feedback['fio']; ?>
		</td>
		<td>
			<?php echo $feedback['contacts']; ?>
		</td>
		<td>
			<?php echo $feedback['text']; ?>
		</td>
		<td>
			<?php echo $feedback['date']; ?>
		</td>
		<td>
			<?php echo $status; ?>
		</td>
		<td>
			<a href="/modules/auth/feedback?operation=close&feedback_id=<?php echo $feedback['id']; ?>" >Закрыть заявку</a>
		</td>
	</tr>
		<?php endforeach; ?>
	<?php endif; ?>
</table>