<ul class="nav nav-pills nav-stacked">
<?php foreach ($list as  $entry): ?>
	<?php $entry['$active'] = $entry['$active'] ? 'class="active"' : ''; ?>
	<?php if (isset($entry['submenu'])&& is_array($entry['submenu'])): ?>
		<li onclick="mainLIclick(this)" id ="<?php echo $entry['id']; ?>"><a data-toggle="tab" href="/#"<?php echo  $entry['url']; ?>&id=<?php echo $entry['id']; ?>"><?php echo $entry['name']; ?></a></li>
		<ul <?php echo $entry['$hidden']; ?> class="nav-pills nav-stacked child children<?php echo $entry['id']; ?>">
		<?php foreach ($entry['submenu'] as  $subEntry): ?>
			<?php $subEntry['$active'] = $subEntry['$active'] ? 'class="active"' : ''; ?>
			<li <?php  echo $subEntry['$active']; ?>  style="line-height: 24px;"><a href="<?php  echo  $subEntry['url'].$ch; ?>id=<?php echo $subEntry['id']; ?>&p_id=<?php echo $subEntry['id_parent']; ?>">
			<span style="padding:0px 0px;"><?php echo $subEntry['name']; ?></span></a></li>
		<?php endforeach; ?>
		</ul>
	<?php else: ?>
	
		<?php if($hasModuleMatchEntry): ?>
			<?php if(isset($module['text'])): ?>
				<li><?php echo $module['text']; ?></li>
			<?php $text = $item; ?>
			<?php endif; ?>
		<?php else: ?>
			<li <?php  echo $entry['$active']; ?> id ="<?php  echo $entry['id']; ?>"><a href="<?php  echo $entry['url']; ?>"><?php  echo $entry['name']; ?></a></li>
		<?php endif; ?>	
	<?php endif; ?>
<?php endforeach; ?>
</ul>


<script>
    function mainLIclick(el) {
		console.log(el);
	    $('ul.nav-pills.child').attr("hidden", "hidden")
	    $('ul.nav-pills.child li').removeClass('active');
	    var str = 'ul.nav-pills.child.children' + el.id;
	    $(str).removeAttr("hidden");
	}
	
</script>