<?php if ($list): ?>
		<?php echo $paginator['text']; ?>
		<?php if ($admin): ?>
			<div align="left">
					<a class="btn btn-success" href="news?operation=edit">Добавить новость<i class="icon-chevron-right icon-white"></i></a>
			</div>
		<?php endif; ?>
			
		<?php foreach ($list as $entry): ?>
			<article class="thumbnail" style="background: #f8f8f0">
				<table id="news" cellpadding="0" cellspacing="0" width="100%" style="padding: 15px 0;">
					<tbody>
						<tr>
							<td valign="top" align="center" width="80">
								<span style="color: #6faa1e; padding: 5px 0;"><?php echo date('d.m.Y H:i',strtotime($entry['date'])); ?></span>
							</td>
							<td valign="top">
								<div style="padding: 0 0 5px 5px;">
									<a href="news?operation=view&id_news=<?php echo $entry['id']; ?>"><?php echo $entry['title']; ?></a>
								</div>
								<div style="padding: 0 0 15px 5px;">
									<a href="news?operation=view&id_news=<?php echo $entry['id']; ?>" style="font-size:12px; text-decoration: none; color: #777777;"><?php echo $entry['annotation']; ?></a>
								</div>
								<?php if ($admin): ?>
								<div align="right">
									<button type="submit" onclick="location.href='news?<?php echo $url;?>id_news=<?php echo $entry['id']; ?>&operation=edit'" class="btn btn-primary"><i class="icon-pencil icon-white"></i>Редактировать</button>
									
									<a class="btn btn-danger confirm-delete" data-id="<?php echo $entry['id']; ?>"><i class="icon-trash icon-white"></i> Удалить</a>
								</div>
								<?php else: ?>
								<div align="right">
									<a class="btn btn-success" href="news?operation=view&id_news=<?php echo $entry['id']; ?>">Читать<i class="icon-chevron-right icon-white"></i></a>
					  			</div>
								<?php endif; ?>
							</td>
						</tr>
					</tbody>
				</table>
			</article><br />

		<?php endforeach; ?>
		
	
		<script type="text/javascript">
			$('.confirm-delete').click(function(e) {
			    e.preventDefault();
			    var id = $(this).data('id');
			    $('#modal-from-dom').data('id', id).modal('show');
				    removeBtn = $('#modal-from-dom').find('.btn-danger')
			    href = removeBtn.attr('href');
			    removeBtn.attr('href', href.replace(/(\d*)id_news=\d*/, 'id_news=' + id));
			})
		</script>
		
		<style>
			button {border: 1px #AAA solid; padding: 4px 10px;}
			.hide {display: none;}​
		</style>
				
		<div id='modal-from-dom' align="center" class='modal hide fade'>
		    <div class='modal-header'>
		      <a href='' class='close'>&times;</a>
		      <h3>Удаление!</h3>
		    </div>
		    <div class='modal-body'>
		      <p>Элемент удаляется без возможности восстановления!</p>
		      <p>Вы уверены что хотите продолжить?</p>
		    </div>
		    <div align="center" class='modal-footer'>
		      <a href='news?<?php echo $url;?>id_news=0&operation=delete' class='btn btn-danger'><i class="icon-remove-circle icon-white"></i>Да</a>
		      <a href="javascript:$('#modal-from-dom').modal('hide')" class="btn btn-primary secondary"><i class="icon-share-alt icon-white"></i>Отмена</a>
		    </div>
		</div>
				
		
	 
	
		<?php echo $paginator['text']; ?>
<?php endif; ?>
	
	