<div class="well">
	<div id="post-164">
		<div class="page-header">
			<h1 style="color:#c5c598;" class="page-title"><?php echo $new['title']; ?></h1>
		</div>
		<div class="post-meta">
			<i class="icon-time"></i><span style="color: #6faa1e; padding: 5px 0;"> <?php echo date('d.m.Y H:i',strtotime($new['date'])); ?></span><br/><br/>
		</div>      
                	
       	<div class="post-entry"><?php echo $new['text']; ?></div>
	</div>
	<hr/>
	
	<div class="post-edit">
		<a href="news?page_num=1">Последние новости:</a>
		<div class="thumbnail">
			<ul>
			<?php if ($latestNews && count($latestNews) > 0): ?>
				<?php foreach ($latestNews as $latestNew): ?>
				<li>
					<a href="news?id_news=<?php echo $latestNew['id']; ?>"><?php echo $latestNew['title']; ?></a>
				</li>
				<?php endforeach; ?>
			<?php endif; ?>
			</ul>
		</div>
	</div><br/>

	<div align="right">
		<a class="btn btn-success" href="/news">Все новости<i class="icon-chevron-right icon-white"></i></a>
	</div>
</div>

