
<form id="serviceFilter" action="/services" method="GET">
	<p>Тип услуги:
		<select name=subservice_digital_form>
		<?php foreach ($subservice_digital_forms as $entry): ?>
			<option value="<?php echo $entry['id']; ?>"	 <?php echo ($subservice_digital_form == $entry['id']) ? ' selected' : ''; ?>><?php echo $entry['name']; ?></option>
		<?php endforeach; ?>
		
		</select>
		Категория заявителей:
		<select name=recipient>
		<?php foreach ($recipients as $entry): ?>
			<option value="<?php echo $entry['id']; ?>" <?php echo  (($recipient == $entry['id']) || ($entry['id'] == 1 && !isset($recipient))) ? ' selected' : ''; ?>><?php echo $text.=$entry['name']; ?></option>';
		<?php endforeach; ?>
		</select>
		<button type="submit" class="btn btn-info"><i class="icon-ok-circle icon-white"></i>Отфильтровать</button>
	</p>
</form>


<?php if ($services): ?>
	<?php echo $paginator['text']; ?>
	<div class="accordion" id="accordion2">
	<?php foreach ($services as $service): ?>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?php echo $service['id']; ?>"><?php echo $service['s_name']; ?></a>
				</div>
		
				<div id="collapse<?php echo $service['id']; ?>" class="accordion-body collapse">
					<div class="accordion-inner">
						<div>Короткое наименование: <?php echo $service['s_short_name']; ?></div>
						<?php if ($service['registry_entry']): ?>
							<div>Административный регламент: <a href="/scripts/import/files.php?reglament_id=<?php echo $service['registry_entry']['id']; ?>"><?php echo $service['registry_entry']['reglament_name']; ?></a></div>
						<?php endif; ?>
						<?php if ($service['company']): ?>
							<div>Организация, ответственная за оказание услуги: <a href="/organisations?operation=view&id_organisation=<?php echo $service['company']['id']; ?>"><?php echo $service['company']['c_name']; ?></a></div>
						<?php endif; ?>
						
						<?php if ($service['subservices_list']): ?>
							<ul>
							<?php foreach ($service['subservices_list'] as $subservice): ?>
								<li><?php echo $subservice['s_short_name']; ?></li>
								<a class="btn btn-success" href="/services?operation=subservice&subservice_id=<?php echo $subservice['id']; ?>">Подробнее<i class="icon-chevron-right icon-white"></i></a>
								<?php if ($subservice['s_digital_form'] == 1 || $subservice['s_digital_form'] == 2): ?>
									<a class="btn btn-success" href="/forms?subservice_id=<?php echo $subservice['id']; ?>">Подать заявление<i class="icon-chevron-right icon-white"></i></a>
								<?php endif; ?>
							<?php endforeach; ?>
							</ul>
						<?php endif; ?>
						
					</div>
				</div>
			</div>
		
	<?php endforeach; ?>
	</div>
	<?php echo $paginator['text']; ?>
<?php endif; ?>