
<h2><?php echo $subservice['s_name']; ?></h2>
<?php if ($subservice['s_digital_form'] == 1): ?>
	<a class="btn btn-success pull-right"	href="/forms?subservice_id=<?php echo $subservice['id']; ?>">Подать заявление<i class="icon-chevron-right icon-white"></i></a>
<?php endif; ?>
<hr/><h4>Краткое наименование</h4>
<div><blockquote class="justify"><?php echo $subservice['s_short_name']; ?></blockquote></div>
<h4>Основание для оказания услуги</h4>
<div><blockquote class="justify"><?php echo $subservice['s_provide_description']; ?></blockquote></div>
<h4>Основание для отказа</h4>
<div><blockquote class="justify"><?php echo $subservice['s_refusal_description']; ?></blockquote></div>
<h4>Результат оказания</h4>
<div><blockquote class="justify"><?php echo $subservice['s_result_description']; ?></blockquote></div>
<h4>Стоимость и порядок оплаты</h4>
<div><blockquote class="justify"><?php echo $subservice['s_payment_description']; ?></blockquote></div>
<h4>Порядок обжалования</h4>
<div><blockquote class="justify"><?php echo $subservice['s_appeal_description']; ?></blockquote></div>
<h4>Форма обращения</h4>
<div><blockquote class="justify"><?php echo ( ($subservice['requests'] != '') ? $subservice['requests'] : 'Не указано' ); ?></blockquote></div>
<h4>Форма ответа</h4>';
<div><blockquote class="justify"><?php echo ( ($subservice['responses'] != '') ? $subservice['responses'] : 'Не указано' ); ?></blockquote></div>
<h4>Нормативно-правовые акты</h4>
<div><blockquote class="justify">Не указаны</blockquote></div>
<h4>Дата размещения услуги</h4>
<div><blockquote class="justify"><?php echo ( ($subservice['approval_date'] != '') ? date('d.m.Y',strtotime($subservice['approval_date'])) : 'Не указано' ); ?></blockquote></div>