<?php if ($service): ?>
	<div><h3><?php echo $service['s_name']; ?></h3></div>
	<div><b>Короткое наименование:</b> <?php echo $service['s_short_name']; ?></div>
	<?php if ($service['reglament']): ?>
	
	<div>
		<b>Административный регламент:</b>	<a href="/scripts/import/files.php?reglament_id=<?php echo $service['reglament']['id']; ?>"><?php echo $service['reglament']['reglament_name']; ?></a>
	</div><br />
	<?php endif; ?>						
	<div>
		<b>Организация, ответственная за оказание услуги:v <a href="/organisations?operation=view&id_organisation=<?php echo $service['company_id']; ?>"><?php echo $service['company_name']; ?></a>
	</div><br />
	<div>
		<b>Порядок обжалования:</b> <?php echo (!empty($service['s_appeal_description']) ? $service['s_appeal_description'] : 'Не указано.'); ?>
	</div><br />
	<div>
		<b>Участники оказания услуги:</b>
		<?php if($service['participants'] && count($service['participants']) > 0): ?>
		<?php foreach ($service['participants'] as $participant): ?>
		<?php echo $participant['title'].' ('.$participant['description'].') - '.$participant['c_name'].'<br />'; ?>												
		<?php endforeach; ?>
		<?php else: ?>
			Не указано											
		<?php endif; ?>
	
	
	</div><br />

	<?php if ($service['subservices']): ?>
		<ul>
		<?php foreach ($service['subservices'] as $subservice): ?>
			<li><?php echo $subservice['s_short_name']; ?></li>
			<a class="btn btn-success" href="/services?operation=subservice&subservice_id=<?php echo $subservice['id']; ?>">Подробнее<i class="icon-chevron-right icon-white"></i></a>
			<?php if ($subservice['s_digital_form']==1 || $subservice['s_digital_form']==2): ?>
				<a class="btn btn-success" href="/forms?subservice_id=<?php echo $subservice['id']; ?>">Подать заявление<i class="icon-chevron-right icon-white"></i></a>
			<?php endif; ?>
		<?php endforeach; ?>
		</ul>
	<?php endif; ?>
<?php endif; ?>