
	
	
							<div class="left">
								<ul class="left_menu">
									<li class="current">Информация об услуге</li>
								</ul>
							</div>
							
							<div class="right">
								<h3><?php echo $service['s_name']; ?></h3>
								<table class="info">
									<tr>
										<td class="first">Короткое наименование</td>
										<td><?php echo $service['s_short_name']; ?></td>
									</tr>						
									<tr>
										<td class="first">Административный регламент</td>
										<td><?php echo  ($service['reglament']['reglament_name'] ? '<a href="/scripts/import/files.php?reglament_id='.$service['reglament']['id'].'">'.$service['reglament']['reglament_name'].'</a>' : '-'); ?></a></td>
									</tr>						
									<tr>
										<td class="first">Ответственный орган</td>
										<td><a href=""><a href="/organisations?operation=view&id_organisation=<?php echo $service['company_id']; ?>"><?php echo $service['company_name']; ?></a></td>
									</tr>
									<tr>
										<td class="first">Получатели</td>
										<td><?php echo $recipients; ?></td>
									</tr>
									<tr>
										<td class="first">Сведения о консультировании</td>
										<td><?php echo $service['consultation'] ? $service['consultation'] : 'Не указано'; ?></td>
									</tr>
									<tr>
										<td class="first">Порядок обжалования</td>
										<td><?php echo (!empty($service['s_appeal_description']) ? $service['s_appeal_description'] : 'Не указано'); ?></td>
									</tr>
									<tr>
										<td class="first">Результат</td>
										<td><?php echo $service['result'] ?  $service['result'] : 'Не указано'; ?></td>
									</tr>						
									<tr>
										<td class="first">Участники оказания услуги</td>
										<td>
										<?php if($service['participants'] && count($service['participants']) > 0): ?>
										<?php foreach ($service['participants'] as $participant): ?>
			 								<?php echo ($participant['title'].' ('.$participant['description'].') - ').$participant['c_name'].'<br /><br />'; ?>												
										<?php endforeach; ?>
										<?php else: ?>
			 								Не указано											
										<?php endif; ?>
										</td>
									</tr>
								</table>
								
								
								<div class="info_block" id="info_block_subservices">
									<div class="info_title">Подуслуги</div><br />
									Электронные: <br />
									<?php if (count($service['subservices'] > 0)): ?>
															
										<?php $i = 0;		
											foreach ($service['subservices'] as $sub): ?>
											<?php if ($sub['s_digital_form'] != 0) : ?>
												<div class="">
													<a href="/services?operation=subservice&subservice_id=<?php echo $sub['id']; ?>"><?php echo $sub['s_name']; ?></a>
												</div><br />
											<?php $i++;
											 	endif; ?>
										<?php endforeach; ?>
									<?php endif; ?>
										
									<?php if ($i == 0): ?>
										<div class="">Отсутствуют<br /><br /></div>
									<?php endif; ?>
									
										Неэлектронные:<br />
									<?php if (count($service['subservices'] > 0)): ?>	
										<?php $i = 0;	
											foreach ($service['subservices'] as $sub): ?>
											<?php if (($sub['s_digital_form'] == 0)): ?>
												<div class="">
													<a href="/services?operation=subservice&subservice_id=<?php echo $sub['id']; ?>"><?php echo $sub['s_name']; ?></a>
												</div><br />
											<?php $i++;
											 	endif; ?>
										<?php endforeach; ?>
									<?php endif; ?>		
												
									<?php if ($i == 0): ?>
										<div class="">Отсутствуют<br /><br /></div>
									<?php endif; ?>		
									
								</div>
										
								<div class="cl"></div>
							</div>
		<!-- 
				<script type="text/javascript">
				$(document).ready(function(){
			    	$("div#content_content").removeClass().addClass("'.( ($recipient == 'phys') ? 'content_disp' : 'content_jur' ).'");
					$("div#content_center").removeClass().addClass("'.( ($recipient == 'phys') ? 'center_disp' : 'center_jur' ).'");
					$("div#content_navigation").html("<a href=\"/\">Главная</a>  / Услуги /  '.$service['s_name'].'");
					$("div.marg_center").prepend("<br /><br />");
					$("div#content_line").removeClass().addClass("'.( ($recipient == 'phys') ? 'green_line' : 'orange_line' ).'");
				});
			</script>
			-->
			
			