<div>Статистика:</div>
<p>Всего описаний услуг: <a href="/services"></a>
	<ul>
		<li>Муниципальных: <a href="/services/type_service_id/1?id=34&p_id=27"><?= $mun_count ?></a></li>
		<li>Государственных: <a href="/services/type_service_id/2?id=33&p_id=27"><?= $gos_count ?></a></li>
	</ul></p>
<p>Услуг в электронном виде: <a href="services/subservice_digital_form/2"><?= $digital_count ?></a></p>
<p>Подуслуг в электронном виде: <a href="services/subservice_digital_form/2"><?= $digital_s_count ?></a></p>
<p>Описаний организаций: <a href="/organisations"><?= $company_count ?></a></p>
<p>Документов: <?= $doc_count ?></p>;
