<style type="text/css" media="screen">
	body { padding:20px;}
	
	.modal.fade {
		top: 10%;
	}
</style>

<form accept-charset="UTF-8" action="/about?operation=save" class="form-horizontal" id="about-edit" method="POST">
<input type="hidden" name="info_id" value="<?php echo $portal_info['id']; ?>" />
<div class="control-group text optional">
	<label class="text optional" for="editor">Содержание: </label>
		<div id="text">
				<?php echo $portal_info['content']; ?>
		</div>
	    <div align="right" class="form-actions">
	           <button type="submit" class="btn btn-success" id="submit_btn"><i class="icon-ok icon-white"></i>Сохранить</button>
				<a class="btn btn-danger" href="/about">Отмена<i class="icon-share-alt icon-white"></i></a>
	    </div>
	</div>
</form>



<!-- elRTE -->
<script src="/elrte/js/elrte.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/elrte/css/elrte.min.css" type="text/css" media="screen" charset="utf-8">
<script src="/elrte/js/i18n/elrte.ru.js" type="text/javascript" charset="utf-8"></script>
<!-- elRTE translation messages -->

<script type="text/javascript" charset="utf-8">
	$().ready(function() {
		var opts = {
			cssClass : 'el-rte',
			lang     : 'ru',
			height   : 450,
			toolbar  : 'complete',
			cssfiles : ['elrte/css/elrte-inner.css']
		};
		$('#text').elrte(opts);

		$('#modal-from-dom').hide();
	});

	$('button#submit_btn').click(function(){
		$('#modal-from-dom').show();
		$('#modal-from-dom').modal({
			backdrop: true
		}).modal('show');
		return false;
	});


	
	function btnok() {
		$('#modal-from-dom').modal('hide');
		$('form#about-edit').submit();
	}
	
</script>

<div id="modal-from-dom" class="modal hide fade">
    <div class="modal-header">
      <a onclick="btnok()" class="close">&times;</a>
      <h3>Сохранение</h3>
    </div>
    <div class="modal-body" align="center">
      <p>Данные успешно сохранены!</p>
    </div>
    <div class="modal-footer">
      <a onclick="btnok()" class="btn btn-success"><i class="icon-info-sign icon-white"></i> Ну и отлично</a>
    </div>
</div>