

<table width="98%" border="0"  style="padding: 10px 15px;">
    <tbody>
        <tr>
            <td align="left" width="60%" valign="top">
            	<?php echo $portal_info['content']; ?>
            </td>
            <td align="right" width="40%" valign="top">
           		<h2>Схема проезда</h2>
           			<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=I-qDvJA-d2MkBzkrQuWSNadjOeLFcOl-&width=450&height=350"></script>
            </td>
        </tr>
    </tbody>
</table>		

<?php if ($admin): ?>
	<div align="left">
		<a class="btn btn-success" href="/about&operation=edit">Редактировать данные<i class="icon-chevron-right icon-white"></i></a>
	</div>
<?php endif; ?>