<div class="statistic_block" style="margin-top: 0px;">
	<div class="in_site">Сейчас на сайте</div>
	<div class="sum">
		<div class="all"> всего <?php echo $service_count; ?></div>
		<div class="disposal">
			<div class="disposal_num"><?php echo $service_count; ?></div>
			<div class="disposal_txt">услуги</div>
		</div>
		<div class="in_detail" align="center">
			<table class="detail_num">
			<!-- 
				<tr>
					<td class="violet"><?php echo $fed_count; ?></td>
					<td>федеральных</td>
					
				</tr>
			 -->							
				<tr>
					<td class="violet"><?php echo $gos_count; ?></td>
					<td>региональных</td>
					
				</tr>							
				<tr>
					<td class="violet"><?php echo $mun_count; ?></td>
					<td>муниципальных</td>
					
				</tr>
			</table>
		</div>
		<div class="function">
			<div class="function_num"><?php echo $digital_s_count; ?></div>
			<div class="function_txt">в эл.виде</div>
		</div>
		<div class="cl"></div>
	</div>
	<div class="also">, также:</div>
	<div class="orgdoc_block">
		<div class="block_bg">
			<div class="bg_organization"><?php echo $company_count; ?></div>
			<div class="block_txt">организаций</div>
		</div>
		<div class="block_bg">
			<div class="bg_doc"><?php echo $doc_count; ?></div>
			<div class="block_txt">документов</div>
		</div>
	</div>
</div>