<div>Статистика:</div>
<p>Всего описаний услуг: <a href="/services"><?php echo $service_count; ?></a>
	<ul>
		<li>Муниципальных: <a href="/services/type_service_id/1?id=34&p_id=27"><?php echo $mun_count; ?></a></li>
		<li>Государственных: <a href="/services/type_service_id/2?id=33&p_id=27"><?php echo $gos_count; ?></a></li>
	</ul></p>
<p>Услуг в электронном виде: <a href="services/subservice_digital_form/2"><?php echo $digital_count; ?></a></p>
<p>Подуслуг в электронном виде: <a href="services/subservice_digital_form/2"><?php echo $digital_s_count; ?></a></p>
<p>Описаний организаций: <a href="/organisations"><?php echo $company_count; ?></a></p>
<p>Документов: <?php echo $doc_count; ?></p>
