<?php 
	include(VIEWS_ROOT."theme/default/templates/search/scripts/onCreate.js");
	if ( (stristr($_SERVER['HTTP_USER_AGENT'], 'Firefox')) ||  stristr($_SERVER['HTTP_USER_AGENT'], 'MSIE 10.0')) {
		include(VIEWS_ROOT."theme/default/templates/search/scripts/indexedDb.js");
	} else  {
		include(VIEWS_ROOT."theme/default/templates/search/scripts/webSql.js");	
	} 
?>


	
<p>Результаты поиска</p>
<form id="searchEngine" name="search_form" style="max-width: 500px;" class="form-search" action="/search" method="GET" onsubmit="return emptySearch();" >
	<input class="search-query" style="width: 200px;" type="text" placeholder="Поиск" name="search_string" id="search_replace" value="<?php echo $search_string; ?>" /><br />
	<label class="checkbox"  id="is_news"><input type="checkbox" name="news_flag" class="checkbox_chk" <?php echo $is_news ? 'checked': ''; ?>> Новости </label>
	<label class="checkbox"><input type="checkbox" name="service_flag" class="checkbox_chk" id="is_service" <?php echo $is_service ? 'checked' : ''; ?>> Услуги </label>
	<label class="checkbox"><input type="checkbox" name="organisation_flag" class="checkbox_chk" id="is_organisation" <?php echo $is_organisation ? 'checked' : ''; ?>> Организации </label><br /><br />
	<label class="checkbox" id="websql_label"><input type="checkbox" name="websql" id="websql" />Поиск по распределенной базе</label><br />
	<button type="submit" class="btn btn-info"><i class="icon-search icon-white"></i>Поиск</button>
</form>

<div id="loader" style="position:relative; display: block; margin:0 auto; text-align:center;">
	<img src="/templates/images/preloader.gif" width="20px" /> &nbsp Идет загрузка данных. Подождите!
</div>
	
	
	

<?php if ($is_news || $is_service || $is_organisation): ?>

		<ul class="nav nav-tabs search_tab">
		<?php $active_tab_created = false; ?>
		<?php if ($is_news): ?>
			<li class="active">
				<a href="search#news" data-toggle="tab" id="news_link" >
					Новости	<?php echo ($news_count == 0) ? '<span class="badge">'.$news_count.'</span>' : '<span class="badge badge-success" id="news_badge">'.$news_count.'</span>'; ?>
				</a></li>
			<?php $active_tab_created = true; ?>
		<?php endif; ?>
		<?php if ($is_service): ?>
			<?php if ($active_tab_created): ?>
				<li>
					<a href="/#services"  data-toggle="tab">
						Услуги
			<?php else: ?>
				<li class="active">
					<a href="/search#services"  data-toggle="tab">
						Услуги
				<?php $active_tab_created = true; ?>
			<?php endif; ?>
			<?php echo ($service_count == 0) ? '<span class="badge" id="service_badge">'.$service_count.'</span>' : '<span class="badge badge-success" id="service_badge">'.$service_count.'</span>'; ?>
					</a>
				</li>
		<?php endif; ?>
		<?php if ($is_organisation): ?>
			<?php if ($active_tab_created): ?>
				<li>
					<a href="/#organisations"  data-toggle="tab">Организации
			<?php else: ?>
				<li class="active">
					<a href="/search#organisations"  data-toggle="tab">Организации
				<?php $active_tab_created = true; ?>
			<?php endif; ?>
			<?php echo ($organisation_count == 0) ? '<span class="badge" id="organisation_badge">'.$organisation_count.'</span>' : '<span class="badge badge-success" id="organisation_badge">'.$organisation_count.'</span>'; ?>
					</a>
				</li>			
		<?php endif; ?>
		
		</ul>
		

		<div class="tab-content">
		<?php $active_pane_created = false; ?>
			
		
		<?php if ($is_news): ?>
			<div class="tab-pane active" id = "news">
			<?php $active_pane_created = true; ?>
			<p>Результаты поиска по новостям:</p>
			<?php if ($news_count != 0): ?>
				<?php if ($news_list): ?>
					<?php echo $paginator['text']; ?>
					<?php foreach ($news_list as $entry): ?>
						<article class="thumbnail" style="background: #f8f8f0">
							<table id="news" cellpadding="0" cellspacing="0" width="100%" style="padding: 15px 0; ">
								<tbody>
									<tr>
										<td valign="top" align="center" width="80">
											<span style="color: #6faa1e; padding: 5px 0;"><?php echo date('d.m.Y H:i',strtotime($entry['date'])); ?></span>
										</td>
										<td valign="top">
											<div style="padding: 0 0 5px 5px;">
												<a href="/news?id_news=<?php echo $entry['id']; ?>"><?php echo $entry['title']; ?></a>
											</div>
											<div style="padding: 0 0 15px 5px;">
												<a href="/news?id_news=<?php echo $entry['id']; ?>" style="font-size:12px; text-decoration: none; color: #777777;"><?php echo $entry['annotation']; ?></a>
											</div>
											<?php if ($admin): ?>
												<div align="right">
													<button type="submit" onclick="location.href='/news?<?php echo $url; ?>id_news=<?php echo $entry['id']; ?>&operation=edit'" class="btn btn-primary"><i class="icon-pencil icon-white"></i>Редактировать</button>
														<a class="btn btn-danger confirm-delete" data-id="<?php echo $entry['id']; ?>"><i class="icon-trash icon-white"></i> Удалить</a>
												</div>
											<?php else: ?>
												<div align="right">
													<a class="btn btn-success" href="/news?id_news=<?php echo $entry['id']; ?>">Читать<i class="icon-chevron-right icon-white"></i></a>
												</div>
											<?php endif; ?>
										</td>
									</tr>
								</tbody>
							</table>
						</article><br>
	
					<?php endforeach; ?>
					<?php echo $paginator['text']; ?>
				<?php endif; ?>
			<?php else: ?>
				<p>Нет новостей, удовлетворяющих запросу</p>
			<?php endif; ?>
			
			</div>
		<?php endif; ?>
		

		<?php if ($is_service): ?>
			<div class="tab-pane <?php echo (!$active_pane_created) ? 'active': ''; ?>" id = "services">
			<?php $active_pane_created = true; ?>
			<p>Результаты поиска по услугам:</p>
			<?php if ($service_count != 0): ?>
				<?php if ($service_list): ?>
					<?php echo $paginator['text']; ?>
					
					<?php foreach ($service_list as $entry): ?>
					
						<article class = "well">
							<span class="label label-info pull-right"><?php echo $entry['type_item']['name']; ?></span>
							<p><a href="/services?operation=view&service_id=<?php echo $entry['id']; ?>"><?php echo $entry['s_short_name']; ?></a></p>
							<p><small><?php echo $entry['s_name']; ?></small></p>
							<p>
								<small>
									Организация ответственная за оказание услуги: <a href="/organisations?operation=view&id_organisation=<?php echo $entry['company_id']; ?>"><?php echo $entry['company_item']['c_name']; ?></a>
								</small>	
							</p>
							<p align="right">
								<a class="btn btn-success" href="/services?operation=view&service_id=<?php echo $entry['id']; ?>">Подробнее<iclass="icon-chevron-right icon-white"></i></a>
							</p>
						</article>
					<?php endforeach; ?>
					
					<?php echo $paginator['text']; ?>
				<?php endif; ?>
			<?php else: ?>
				<p>Нет услуг, удовлетворяющих запросу</p>
			<?php endif; ?>
			</div>
		<?php endif; ?>
		
			
		<?php if ($is_organisation): ?>
			<div class="tab-pane <?php echo (!$active_pane_created) ? 'active': ''; ?>" id = "organisations">
			<?php $active_pane_created = true; ?>
			<p>Результаты поиска по организациям:</p>
			<?php if ($organisation_count != 0): ?>
				<?php if ($organisation_list): ?>
					<?php echo $paginator['text']; ?>
					
					<?php foreach ($organisation_list as $entry): ?>
						<article class = "well">
							<span class="label label-info pull-right"><?php echo $entry['type_item']['name']; ?></span>
							<p><a href="/organisations?operation=view&id_organisation=<?php echo $entry['id']; ?>"><?php echo $entry['c_name']; ?></a></p>
							<p><small>Руководитель: <?php echo $entry['c_head']; ?></small></p>
							<p><small><a href="<?php echo $entry['c_web_site']; ?>">Официальный сайт</a></small></p>
							<p>Контактная информация: <?php echo $entry['c_contacts']; ?></p>
							<p align="right">
								<a class="btn btn-success" href="/organisations?operation=view&id_organisation=<?php echo $entry['id']; ?>">Подробнее<i class="icon-chevron-right icon-white"></i></a>
							</p>
						</article>
					<?php endforeach; ?>
					
					<?php echo $paginator['text']; ?>
				<?php endif; ?>
			<?php else: ?>
				<p>Нет организаций, удовлетворяющих запросу</p>
			<?php endif; ?>
			</div>
		<?php endif; ?>
		
	
	</div>

	<?php else: ?>
		<p>Не выбраны критерии для поиска</p>
	<?php endif; ?>	
	
	<div id="details"></div>
	
	
	
	
<script type="text/javascript">
	$("input#websql").change(function(){
		if ($(this).attr("checked")) {
			$("#is_news").hide();
			$("#news").css("vicibiliy", "hidden");
			$("ul li a#news_link").hide();
			$("form#searchEngine").attr("action", "#").attr("method", "").attr("onsubmit", "return processInfo();");
			return false;
		} else {
			$("#is_news").show();
			$("#news").css("vicibiliy", "visible").html("<p>Результаты поиска по новостям: </p><p>Нет новостей, удовлетворяющих запросу</p>");
			$("#news_badge").text("0").removeClass("badge-success");
			$("ul li a#news_link").show();
			$("form#searchEngine").attr("action", "search?is_news=true&is_service=true&is_organisation=true").attr("method", "GET").attr("onsubmit", "return emptySearch();");
		}
	});
	 
	function emptySearch(){
		if($("#search_replace").val() == "") {
			alert("Поле поиска не может быть пустым!");
			return false;
		}
			
	};

	$(document).ready(function(){
		$("#loader").hide();
	});

</script>