
 
<h3 class="title_cabinet">Личный кабинет</h3>
<div class="rule"></div><br />
	
	

<table class="table table-bordered">
	<tr>
		<td width="50%"><b>Услуга</b></td>
		<td><b>Комментарий</b></td>
		<td><b>Дата подачи</b></td>
		<td>Статус отправки</td>
		<td></td>
	</tr>
	<?php if ($requests): ?>
	<?php foreach ($requests as $request): ?>	    
	<tr>
		<td>
			
			<?php echo $request['s_name']; ?>
			
		</td>
		<td>
			<?php echo $request['comment']; ?>
		</td>
		<td>
			<?php echo $request['time']; ?>
		</td>
		<td>
		<?php if ($request['state'] == 7): ?>
			<span class="in_line_msg">В ведомстве</span>
		<?php endif; ?>
		<?php if ($request['state'] == 8): ?>
			<span class="in_smev_msg">В обработке</span>
		<?php endif; ?>
		<?php if ($request['state'] == 9): ?>
			<span class="error_msg">Отказано в предоставлении услуги</span>
		<?php endif; ?>
		<?php if ($request['state'] == 10): ?>
			<span class="success_msg">Выполнено</span>
		<?php endif; ?>
		</td>
		<td>	
			<?php 	$checkStatusFile = CONTROLLERS_ROOT."forms/status/check_".$request['registry_number'].".php";
		    if(file_exists($checkStatusFile)): ?>
	    		<?php if ($request['state'] == 11): ?>
	    			<?php $url_tmp = '/forms?request_id='.$request['id_request'].'&subservice_id='.$request['id_subservice'].'&outId='.$request['id_out']; ?>
	    			<?php if (isset($request['user_action'])&&$request['user_action']!=""): ?>
	    				<?php $url_tmp .= '&user_action='.$request['user_action']; ?>
	    			<?php endif; ?>
	    				<a href="<?php echo $url_tmp; ?>" >Продолжить</a>
	    		<?php else: ?>
	    			<a href="/account?request_id=<?php echo $request['id_request'].'&id_subservice='.$request['id_subservice'].'&outId='.$request['id_out']; ?>" >Проверить</a>
	    		<?php endif; ?>
			<?php endif; ?>
					
			<?php $cancelFile = CONTROLLERS_ROOT."forms/cancels/cancel_".$request['registry_number'].".php";
			if (file_exists($cancelFile)): ?>
				<?php $url_tmp = '/forms?request_id='.$request['id_request'].'&subservice_id='.$request['id_subservice'].'&outId='.$request['id_out'].'&action='.$request['user_action']; ?>
				<?php if ($request['user_action'] == 'doctor'): ?>
					<?php if ($request['id_out'] == '0'): ?>
						
					<?php else: ?>
						<script src="/templates/assets/js/doctors.js"></script>
						<a href="#" id="cancelBtn" idOut="<?php echo $request['id_out']; ?>" reqSub="<?php echo $request['id_request'].'&'.$request['id_subservice']; ?>" onclick="cancelDoctor(this);">Отменить</a>				
					<?php endif; ?>
				<?php else: ?>				
					<a href="<?php echo $url_tmp; ?>" id="cancelBtn">Отменить</a>
				<?php endif; ?>	
			<?php endif; ?>
		</td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
    	$("div#content_content").removeClass().addClass("content");
		$("div#content_center").removeClass().addClass("center");
		$("div#content_navigation").html("<a href=\"/\">Главная</a>  / Личный кабинет");
		$("div#content_line").removeClass().addClass("blue_linecab").html("<div class=\"sub_menucab\">	<!-- <ul class=\"topsub_menucab\"> <li><a href=\"#\">Заявления</a></li> <li><a href=\"#\">Черновики</a></li> <li><a href=\"#\">Платежи</a></li> <li><a href=\"#\">Обучение</a></li> <li><a href=\"#\">Заметки</a></li> <li><a href=\"#\">Избранное</a></li> <li class=\"current\">Настройки</li> </ul> --> <div class=\"cl\"></div>");
	});
</script>
<script type="text/javascript">
	function cancelDoctor(el) {
		var reqSub = $(el).attr("reqSub").split("&");
		
		doctorRecordCancel($(el).attr("idOut"), reqSub[0], reqSub[1]);
	}		 
</script>