<?php 
include(VIEWS_ROOT."theme/default/templates/search/scripts/onCreate.js");
if ( (stristr($_SERVER['HTTP_USER_AGENT'], 'Firefox')) ||  stristr($_SERVER['HTTP_USER_AGENT'], 'MSIE 10.0')) {
	include(VIEWS_ROOT."theme/default/templates/search/scripts/indexedDb.js");
} else  {
	include(VIEWS_ROOT."theme/default/templates/search/scripts/webSql.js");	
} 


?>


<h3 class="title_blank">Результаты поиска</h3>
<div class="search_block">
	<div class="request">Ваш запрос:</div>

	<form id="searchEngine" name="search_form" class="form-search search-form-index" action="/search" method="GET" >
		<div style="display: none;">
			<input type="checkbox" name="news_flag" class="checkbox_chk" <?php echo $_GET['news_flag'] ? 'checked': ''; ?>>
			<input type="checkbox" name="service_flag" class="checkbox_chk" id="is_service" <?php echo  $_GET['service_flag'] ? 'checked' : ''; ?>>
			<input type="checkbox" name="organisation_flag" class="checkbox_chk" id="is_organisation" <?php echo $_GET['organisation_flag'] ? 'checked' : ''; ?>>
		</div>
		
		<input class="search-query wh" type="text" placeholder="Поиск" name="search_string" id="search_replace" value="<?php echo $_GET['search_string']; ?>"/>
		<button class="search_btn" onclick="emptySearch();">Найти</button>
	</form>
					
	<div class="cl"></div>
	<div class="request">Показать в результатах поиска:</div>
				
	<div class="search_menu search_tabs">
		<ul class="list_search search_tabNavigation">
		<?php $url = $_SERVER[REQUEST_URI]; ?>
			<li class="<?php echo ( ( strpos($url,'news_flag') !== false && strpos($url,'organisation_flag') !== false && strpos($url,'service_flag') !== false ) ? 'current' : '' ); ?>" id="search_block_all"><a class="srch" onclick="search_block_change(this);">Все</a></li>
			<li class="<?php echo ( ( strpos($url,'news_flag') === false && strpos($url,'organisation_flag') === false && strpos($url,'service_flag') !== false ) ? 'current' : '' ); ?>" id="search_block_services"><a class="srch" onclick="search_block_change(this);">Услуги</a></li>
			<li class="<?php echo ( ( strpos($url,'news_flag') === false && strpos($url,'organisation_flag') !== false && strpos($url,'service_flag') === false ) ? 'current' : '' ); ?>" id="search_block_organisations"><a class="srch" onclick="search_block_change(this);">Организации</a></li>
			<li class="<?php echo ( ( strpos($url,'news_flag') !== false && strpos($url,'organisation_flag') === false && strpos($url,'service_flssag') === false ) ? 'current' : '' ); ?>" id="search_block_news"><a class="srch" onclick="search_block_change(this);">Новости</a></li>
		</ul>
	</div>
	<div class="cl"></div>
</div>
				
	
<div class="search_result search_result_block">	
<?php define('All_SEARCH_RESULT_COUNT', 10); ?>

<?php if ($is_news && $is_organisation && $is_service): ?>
	<div id="search_block_all">
		<?php if ($search_list): ?>
			<ol class="result">
			<?php if ($news_count > 0): ?>
				<h3>Новости</h3><br />
				<?php $i = 0;
					foreach ($search_list as $item): ?>
					<?php if ($item['table'] == 'news'): ?>
						<li><a href="news?id_news=<?php echo $item['id']; ?>"><?php echo $item['title']; ?></a></li>	
						<?php $i++; if ($i == All_SEARCH_RESULT_COUNT): ?>
							<a class="more_info" id="more_news" onclick="moreSearchResults(this);">Подробнее...</a><br />
						<?php break; endif; ?>
					<?php endif; ?>									
				<?php endforeach; ?>
			<?php else: ?>
				<h3>Новости</h3><br /><p>По данному запросу новостей не найдено!</p>
			<?php endif; ?>
				
			<?php if ($organisation_count > 0): ?>
				<br /><h3>Организации</h3><br />
				<?php $i = 0;
					foreach ($search_list as $item): ?>
					<?php if ($item['table'] == 'organisations'): ?>
							<li><a href="organisations?operation=view&id_organisation=<?php echo $item['id']; ?>"><?php echo $item['title']; ?></a></li>
							<?php $i++; if ($i == All_SEARCH_RESULT_COUNT): ?>
								<a class="more_info" id="more_organisations" onclick="moreSearchResults(this);">Подробнее...</a><br />
							<?php break; endif; ?>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php else: ?>
				<br /><h3>Организации</h3><br /><p>По данному запросу организаций не найдено!</p>
			<?php endif; ?>
				
			<?php if ($service_count > 0): ?>
				<br /><h3>Услуги</h3><br />
				<?php $i = 0;
					foreach ($search_list as $item): ?>
					<?php if ($item['table'] == 'services'): ?>
						<li><a href="services?operation=view&service_id=<?php echo $item['id']; ?>"><?php echo $item['title']; ?></a></li>
						<?php $i++;
							if ($i == All_SEARCH_RESULT_COUNT): ?>
								<a class="more_info" id="more_services" onclick="moreSearchResults(this);">Подробнее...</a><br />
						<?php break; endif; ?>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php else: ?>
				<br /><h3>Услуги</h3><br /><p>По данному запросу услуг не найдено!</p>
			<?php endif; ?>	
			</ol>
		<?php  else: ?>
			По Вашему запросу ничего не найдено.							
		<?php endif; ?>	
	</div>

<?php elseif ($is_news || $is_organisation || $is_service): ?>	
	<?php if ($is_news): ?>
		<div id="search_block_news">
		<?php if ($news_count != 0): ?>
			<?php if ($news_list): ?>
				<ol class="result">			
				<?php $i = 0; foreach ($news_list as $entry): ?>
					<li><a href="/news?id_news=<?php echo $entry['id']; ?>" ><?php echo $entry['annotation']; ?></a></li>
				<?php 		endforeach; ?>
				</ol>
				<?php echo $paginator['text']; ?>
			<?php endif; ?>
		<?php else: ?>
			<p>Нет новостей, удовлетворяющих запросу</p>
		<?php endif; ?>
		</div>
	<?php endif; ?>
		
	<?php if ($is_service): ?>
		<div id="search_block_services">
		<?php if ($service_count != 0): ?>
			<?php if ($service_list): ?>		
				<ol class="result">
				<?php foreach ($service_list as $entry): ?>
					<li><a href="/services?operation=view&service_id=<?php echo $entry['id']; ?>"><?php echo $entry['s_short_name']; ?></a></li>
				<?php endforeach; ?>
				</ol>
			<?php echo $paginator['text']; ?>
			<?php endif; ?> 
		<?php else: ?>
			<p>Нет услуг, удовлетворяющих запросу</p>
		<?php endif; ?>
		</div>
	<?php endif; ?>
		
	<?php if ($is_organisation): ?>
		<div id="search_block_organisations">
		<?php if ($organisation_count != 0): ?>
			<?php if ($organisation_list): ?>	
				<ol class="result">
				<?php foreach ($organisation_list as $entry): ?>
					<li><a href="/organisations?operation=view&id_organisation=<?php echo $entry['id']; ?>"><?php echo $entry['c_name']; ?></a></li>
				<?php endforeach; ?>
				</ol>
				<?php echo $paginator['text']; ?>
			<?php endif; ?>
		<?php else: ?>
			<p>Нет организаций, удовлетворяющих запросу</p>
		<?php endif; ?> 
		</div>
	<?php endif; ?>
						
<?php endif; ?>

</div>
	

	<script type="text/javascript">
					$(document).ready(function(){
				        var url = window.location.href;
						var text_link;   
						if ( url.indexOf("service_flag") != -1 && url.indexOf("organisation_flag") != -1 && url.indexOf("news_flag") != -1 ) {
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_all a").text();
							$("div.search_tabs ul.search_tabNavigation li#search_block_all").text(text_link);
						} else if ( url.indexOf("service_flag") != -1 && url.indexOf("organisation_flag") == -1 && url.indexOf("news_flag") == -1 ) {
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_services a").text();
							$("div.search_tabs ul.search_tabNavigation li#search_block_services").text(text_link);
						} else if( url.indexOf("service_flag") == -1 && url.indexOf("organisation_flag") != -1 && url.indexOf("news_flag") == -1 ) {
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_organisations a").text();
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_organisations").text(text_link);
						} else if ( url.indexOf("service_flag") == -1 && url.indexOf("organisation_flag") == -1 && url.indexOf("news_flag") != -1 ) {
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_news a").text();
							text_link = $("div.search_tabs ul.search_tabNavigation li#search_block_news").text(text_link);
						}
						
						$('div#content_content').removeClass().addClass('content');
						$('div#content_center').removeClass().addClass('center');
						$('div#content_navigation').html('<a href="/">Главная</a>  / Результаты поиска');
						$('div#content_line').removeClass().addClass('blue_line');
					});
	
					
					function emptySearch(){
						if($('#search_replace').val() == '') {
							alert('Поле поиска не может быть пустым!');
						return false;
						}
				
						var search_name = $('div.search_tabs ul.search_tabNavigation li.current').attr('id').split('_').pop();
						var search_string = $('form.search-form-index input[name="search_string"]').val();

						$('form.search-form-index input[name="news_flag"]').removeAttr('checked');
						$('form.search-form-index input[name="organisation_flag"]').removeAttr('checked');
						$('form.search-form-index input[name="service_flag"]').removeAttr('checked');
						
						if ( search_name == 'all') {
								$('form#searchEngine').attr('action', "/search?search_string=<?php echo $search_string; ?>&is_news=on&is_service=on&is_organisation=on").attr('method', 'GET');
								$('form.search-form-index input[name="news_flag"]').attr('checked', 'checked');
								$('form.search-form-index input[name="service_flag"]').attr('checked', 'checked');
								$('form.search-form-index input[name="organisation_flag"]').attr('checked', 'checked');
							} else if (search_name == 'services'){
								$('form#searchEngine').attr('action', "/search?search_string=<?php echo $search_string; ?>&is_service=on").attr('method', 'GET');		
								$('form.search-form-index input[name="service_flag"]').attr('checked', 'checked');
							} else if (search_name == 'organisations'){
								$('form#searchEngine').attr('action', "/search?search_string=<?php echo $search_string; ?>&is_organisation=on").attr('method', 'GET');
								$('form.search-form-index input[name="organisation_flag"]').attr('checked', 'checked');
							} else if (search_name == 'news'){
								$('form#searchEngine').attr('action', "/search?search_string=<?php echo $search_string; ?>&is_news=on").attr('method', 'GET');
								$('form.search-form-index input[name="news_flag"]').attr('checked', 'checked');
							}	
							
							$('form[name="search_form"]').submit();
					};
				</script>