
<script type="text/javascript">
	function info_block_change(el){
		$("div.info_block").hide();

		var block_name = $(el).parent("li").attr("id").split("_").pop(); // Определение наименования показываемого блока (services, organizations  и т.д.)
		
		// Определяем текст в кликнутой ссылке и текст в текущей вкладке, чтобы поменять местами. 
		var link_text = $(el).text();
		var current_link = $("div.left ul.left_menu li.current");   
		var prev_link_text = current_link.text();
		
		current_link.removeClass("current").html("<a class=\"menu_link\"  onclick=\"info_block_change(this);\" >" + prev_link_text + "</a>");
		$(el).parent("li").text(link_text).addClass("current");
		
		
		$("div#info_block_" + block_name).show();
	};

</script>