<script type="text/javascript">
	$(document).ready(function(){
		$("div.info_block").hide();

		<?php if ($recipient != 'all'): ?>			
	    	$("div#content_content").removeClass().addClass("<?php echo ( ($recipient == 'phys') ? 'content_disp' : 'content_jur' ); ?>")
			$("div#content_center").removeClass().addClass("<?php echo ( ($recipient == 'phys') ? 'center_disp' : 'center_jur' ); ?>");
			
			
			var navigation_menu = '<div class="nav_menu">' + 
									'<ul class="topnav_menu">' + 
									<?php $first_menu = true; ?>
									<?php if($menu_categories): ?>
										<?php foreach ($menu_categories as $item): ?>	
											<?php if ($item['category_id'] == $item['id']): ?>
											'<li class="current"><?php echo $item['short_name']; ?></li>' +
											<?php $first_menu = false; ?>
											<?php else: ?>
											'<li><a href="/services?service_categories=<?php echo $item['id']; ?>"><?php echo $item['short_name']; ?></a></li>' +											
											<?php endif; ?>
										<?php endforeach; ?>
									<?php endif; ?>
												
									
									'</ul>' + 
									'<div class="cl"></div>' + 
									'</div>';
	
			$("div.marg_center").prepend(navigation_menu);													
			$("div#content_navigation").removeClass().addClass("navigation_disposal");
			

			var text_nav = '<a href="/">Главная</a>  / ';
			<?php if($menu_categories): ?> 
				<?php foreach ($menu_categories as $item): ?>	
					<?php if ($item['category_id'] == $item['id']): ?>				
					text_nav += <?php echo '"'.$item['short_name'].'"'; ?>;
					<?php endif; ?> 
				<?php endforeach; ?>
			<?php endif; ?>

			$("div#content_navigation").html(text_nav);
					
			$("div#content_line").removeClass().addClass("<?php echo ( ($recipient == 'phys') ? 'green_line' : 'orange_line' ); ?>");
		<?php endif; ?>
	});
</script>
		