

<div class="content"><img name="map_region" src="/templates/images/map_region.jpg" class="mapper" width="718" height="452"  border="0" id="map_region" usemap="#regions" alt="" />
<map name="regions" id="regions">

<?php foreach ($regions_list as $region): ?>
	<area shape="poly" coords="<?php echo $region['coord']; ?>" region_id="<?php echo $region['id']; ?>" href="<?php echo $region['link']; ?>" alt="<?php echo $region['name']; ?>"  class="noborder icolor000000" />
<?php endforeach; ?>

</map></div>