<div class="rule"></div>
<h3 class="title_blank">Новости</h3>

<?php if ($admin): ?>				
	<div align="left">
		<a class="btn btn-success" href="news?operation=create">Добавить новость<i class="icon-chevron-right icon-white"></i></a>
	</div>
<?php endif; ?>
							
<?php echo $paginator['text']; ?>
<?php foreach ($list as $entry): ?>							
	<div class="news_list">
		<div class="news_info">
			<div class="news_data1"><?php echo date('d.m.Y H:i',strtotime($entry['date'])); ?></div>
			<div class="news_txt1"><a href="news?operation=view&id_news=<?php echo $entry['id']; ?>"><?php echo $entry['title']; ?></a></div>
			<?php if ($admin): ?>
				<div align="right">
					<button type="submit" onclick="location.href='news?<?php echo $url;?>id_news=<?php echo $entry['id']; ?>&operation=edit'" class="btn btn-primary"><i class="icon-pencil icon-white"></i>Редактировать</button>
					
					<a class="btn btn-danger confirm-delete" data-id="<?php echo $entry['id']; ?>"><i class="icon-trash icon-white"></i> Удалить</a>
				</div>
			<?php endif; ?>
		</div>
		<div class="cl"></div>
	</div>
<?php endforeach; ?>
<?php echo $paginator['text']; ?>	
		
							
<script type="text/javascript">
	$(document).ready(function(){
    	$('div#content_content').removeClass().addClass('content');
		$('div#content_center').removeClass().addClass('center');
		$('div#content_navigation').html('<a href="/">Главная</a>  / Новости');
		$('div#content_line').removeClass().addClass('blue_line');
	});

	$('.confirm-delete').click(function(e) {
	    e.preventDefault();
	    var id = $(this).data('id');
	    $('#modal-from-dom').show();
	    $('#modal-from-dom').data('id', id).modal('show');
		    removeBtn = $('#modal-from-dom').find('.btn-danger')
	    href = removeBtn.attr('href');
	    removeBtn.attr('href', href.replace(/(\d*)id_news=\d*/, 'id_news=' + id));
	})
</script>

<style>
	button {border: 1px #AAA solid; padding: 4px 10px;}
	.hide {display: none;}​
</style>
		
<div id='modal-from-dom' align="center" class='modal hide fade' style="margin-top: 385px;">
    <div class='modal-header'>
      <a href='' class='close'>&times;</a>
      <h3>Удаление!</h3>
    </div>
    <div class='modal-body'>
      <p>Элемент удаляется без возможности восстановления!</p>
      <p>Вы уверены что хотите продолжить?</p>
    </div>
    <div align="center" class='modal-footer'>
      <a href='news?<?php echo $url;?>id_news=0&operation=delete' class='btn btn-danger'><i class="icon-remove-circle icon-white"></i>Да</a>
      <a href="javascript:$('#modal-from-dom').modal('hide')" class="btn btn-primary secondary"><i class="icon-share-alt icon-white"></i>Отмена</a>
    </div>
</div>