<div class="news">
<?php for($i = 0; $i < (count($last_news)); $i++): ?>
	<?php if ($i == 0): ?>
	<div class="news_block">
		<div class="news_title">Новости</div>
		<div class="news_data"><?php echo $last_news[$i]['date']; ?></div>
		<div class="news_txt"><a href="/news?id_news=<?php echo $last_news[$i]['id']; ?>"><?php echo $last_news[$i]['title']; ?></a></div>
		<div class="all_news"><a href="/news">Все новости</a></div>
	</div>					
	<?php elseif($i != count($last_news) - 1): ?>							
	<div class="news_block">
		<div class="news_data pad"><?php echo $last_news[$i]['date']; ?></div>
		<div class="news_txt pad_txt"><a href="/news?id_news=<?php echo $last_news[$i]['id']; ?>"><?php echo $last_news[$i]['title']; ?></a></div>
	</div>
	<?php else: ?>
	<div class="news_block bord">
		<div class="news_data pad"><?php echo $last_news[$i]['date']; ?></div>
		<div class="news_txt pad_txt"><a href="/news?id_news=<?php echo $last_news[$i]['id']; ?>"><?php echo $last_news[$i]['title']; ?></a></div>
	</div>						
	<?php endif; ?>
<?php endfor; ?>
	<div class="cl"></div>
</div>